name: github_action_ci

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and test in Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Dockerhub Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker image
        run: docker build -t ci-cd-example .
      - name: taging
        run: docker tag ci-cd-example:latest ${{secrets.DOCKERHUB_USERNAME}}/ci-cd-example:latest
      - name: push to Dockerhub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/ci-cd-example:latest
